create table if not exists "user" (
    "id" int primary key generated by default as identity,
    "name" varchar(128) not null unique
);

--;;

create table if not exists "thing" (
    "id" int primary key generated by default as identity,
    "name" varchar(128) not null unique
);

--;;

create table if not exists "users_things" (
    "user_id" int not null references "user" ("id"),
    "thing_id" int not null references "thing" ("id"),
    "quantity" int not null default 1
);
